---
# tasks file for docker_install

- name: 'Install docker using apt repos'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-apt
    - python3-pip
    state: latest
    update_cache: true

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    

- name: Add docker stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Update apt and install docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: true
    state: latest

- name: install docker module for python
  pip:
    name: docker

