apiVersion: v1
kind: Service
metadata:
  name: magic-db
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Pod
metadata:
  name: magic-db
  labels:
    app: mysql
spec:
  containers:
  - name: magic-db
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: rootPassword
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: credentials
          key: database
