apiVersion: v1
kind: Service
metadata:
  name: service-4
spec:
  type: ClusterIP
  selector:
    app: magic8ball
    svc: "4"
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000        

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-4
  labels:
    app: magic8ball
    svc: "4"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magic8ball
      svc: "4"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: magic8ball
        svc: "4"
    spec:
      containers:
      - name: service-4
        image: gregnemeth/service-4
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: rootPassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: credentials
              key: database
