apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: magic8ball
    svc: "1"
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels:
    app: magic8ball
    svc: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magic8ball
      svc: "1"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: magic8ball
        svc: "1"
    spec:
      containers:
      - name: service-1
        image: gregnemeth/service-1
        ports:
        - containerPort: 5000
