steps:
# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
  dir: magic8ball

# Run unit tests
- name: python
  entrypoint: python
  args: ["-m", "pytest", "--cov=.","--junitxml=${SHORT_SHA}_test_log.xml"]
  dir: magic8ball

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  dir: magic8ball
  args: ['build', '-t', 
         'gcr.io/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']
         
# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "gcr.io/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA']
