steps:
# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
  dir: magic8ball

# Run unit tests
- name: python
  entrypoint: python
  args: ["-m", "pytest", "--cov=.","--junitxml=${SHORT_SHA}_test_log.xml"] 
  logging: CLOUD_LOGGING_ONLY    
  dir: magic8ball

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
         'europe-west2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']
         
# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'europe-west2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA']
