steps:
# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
  dir: magic8ball

# Run unit tests
- name: python
  entrypoint: python
  args: ["-m", "pytest", "--cov=.","--junitxml=${SHORT_SHA}_test_log.xml"]
  dir: magic8ball

# Docker Build
- name: 'europe-west2-docker.pkg.dev/sunlit-theory317815/gregs-gcp-image-repo/cl-doccomp:latest'
  dir: magic8ball
  args: ['build','--parallel']
         
# Docker Push
- name: 'europe-west2-docker.pkg.dev/sunlit-theory317815/gregs-gcp-image-repo/cl-doccomp:latest'
  dir: magic8ball
  args: [push]
