pipeline{
    agent any
    stages{
        stage('Testing'){
            steps{
                sh '''
                    cd magic8ball
                    bash scripts/tests.sh
                    '''
            }
        }
    }
}